import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.scss";
import React from "react";
//MUI

import { styled } from "@mui/material/styles";
import { Grid, Container, Typography } from "@mui/material";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/main-logo.png" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <style>
          {`
            body {
              margin: 0;
              background-color: #FAFAFA;
            }
          `}
        </style>
      </Head>
      <main>
        <Grid container height="100vh">
          <Grid
            item
            md={2.5}
            sx={{
              boxShadow: "1px 1px 5px 0px rgba(0,0,0,0.52)",
              backgroundColor: "#FFFFFF",
              height: "100vh",
            }}>
            <Container sx={{ mt: "20px" }}>
              <Typography variant="h4" component="h2">
                SignalMate
              </Typography>
            </Container>
          </Grid>
        </Grid>
      </main>
    </>
  );
}
